### ISSUE TITLE
cannot continue past clearfog first time setup menu

### ISSUE THREAD

**Issue by Tiecoon** [spr-networks/super#339]
when attempting to hit save at first time setup screen on the clearfog device, nothing happens and this error is thrown inside the web console
```
Wifi.js:429 Uncaught TypeError: Cannot set properties of undefined (setting 'he_mu_beamformer')
    at eh (Wifi.js:429:19)
    at d (Setup.js:276:27)
    at ie (Setup.js:275:5)
    at onClick (PressResponder.js:310:13)
    at Object.De (react-dom.production.min.js:54:317)
    at Be (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Nr (react-dom.production.min.js:105:68)
    at $r (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104```

**Comment by lts-rad** [comment]
https://github.com/spr-networks/super/commit/12283a963b1546fd9853da0420f1d142d59c0b48

**Comment by Tiecoon** [comment]
Thank you! dev branch worked.
